import os

# Read the original working version to get clean base
# We'll write the complete new version via this script

lines = []
A = lines.append

A('"""')
A('TopDown Shooter v4 - with Boss System')
A('操作：WASD移动 鼠标瞄准 左键射击 M换弹 ESC暂停')
A('"""')
A('import pygame, math, random, sys, array, struct, json, os')
A('')
A('try:')
A('    import ctypes')
A('    if sys.platform == "win32":')
A('        ctypes.windll.user32.ShowWindow(ctypes.windll.kernel32.GetConsoleWindow(), 0)')
A('except Exception:')
A('    pass')
A('')
A('# === Config ===')
A('W, H    = 800, 600')
A('FPS    = 60')
A('SR     = 22050')
A('')
A('# === Colors ===')
A('C_BG       = (18,  18,  28)')
A('C_GRID     = (28,  28,  42)')
A('C_PLAYER   = (70, 200, 120)')
A('C_PLAYER_G = (160, 220, 180)')
A('C_BULLET   = (255, 240,  70)')
A('C_E1       = (210,  55,  55)')
A('C_E2       = (220, 115,  25)')
A('C_E3       = (150,  40, 195)')
A('C_HP_BG    = (55,  18,  18)')
A('C_HP_FG    = (210,  55,  55)')
A('C_TEXT     = (235, 235, 235)')
A('C_TEXT_D   = (130, 130, 150)')
A('C_ACCENT   = (255, 215,  50)')
A('C_WARN     = (255,  90,  90)')
A('C_COVER    = (65,  65,  90)')
A('C_COVER_E  = (90,  90, 120)')
A('C_POVER_BG = (0,   0,   0, 170)')
A('C_BOSS     = (255, 50,  50)')
A('C_BOSS_2   = (255, 180, 30)')
A('C_BOSS_BUL = (255, 100, 60)')
A('')
A('# === Game Params ===')
A('PLAYER_SPD = 3.5')
A('PLAYER_R   = 14')
A('BULLET_SPD = 9.5')
A('BULLET_R   = 4')
A('SHOOT_CD   = 160')
A('MAX_BULLETS= 50')
A('RELOAD_MS  = 1400')
A('')
A('# === Globals (cheat-overridable) ===')
A('g_bullet_r  = BULLET_R')
A('g_shoot_cd  = SHOOT_CD')
A('g_bullet_dmg= 1')
A('g_reload_ms = RELOAD_MS')
A('')
A('# === Levels ===')
A('LEVELS = [')
A('    (8,   2000, 0, 12, 48),')
A('    (12,  1800, 2, 12, 48),')
A('    (16,  1600, 3, 15, 60),')
A('    (20,  1400, 3, 15, 60),')
A('    (25,  1200, 4, 18, 72),')
A('    (30,  1000, 4, 18, 72),')
A('    (35,   850, 5, 22, 88),')
A('    (40,   700, 5, 22, 88),')
A('    (50,   600, 6, 26, 104),')
A('    (60,   500, 6, 30, 120),')
A(']')
A('BOSS_LEVELS = {4, 9}')
A('BOSS_HP     = [50, 100]')
A('BOSS_R      = 36')
A('BOSS_FIRE_CD= [900, 600]')
A('BOSS_BUL_SPD= 3.5')
A('')
A('')
A('def dist(a, b):')
A('    dx, dy = a[0]-b[0], a[1]-b[1]')
A('    return math.sqrt(dx*dx + dy*dy)')
A('')
A('def angle_to(src, dst):')
A('    return math.atan2(dst[1]-src[1], dst[0]-src[0])')
A('')
A('def clamp(v, lo, hi):')
A('    return max(lo, min(hi, v))')
A('')
A('# === Sound ===')
A('def make_sound(gen_func):')
A('    try:')
A('        buf = gen_func()')
A('        if buf:')
A('            return pygame.mixer.Sound(buffer=buf)')
A('    except Exception:')
A('        pass')
A('    return None')
A('')
A('def tone(freq, dur, vol=0.3, wave="sine"):')
A('    n = int(SR * dur)')
A('    buf = bytearray(n * 2)')
A('    for i in range(n):')
A('        t = i / SR')
A('        env = max(0.0, 1.0 - t / dur)')
A('        v = 0.0')
A('        if wave == "sine":')
A('            v = math.sin(2.0 * math.pi * freq * t)')
A('        elif wave == "square":')
A('            v = 1.0 if math.sin(2.0 * math.pi * freq * t) >= 0 else -1.0')
A('        elif wave == "saw":')
A('            v = 2.0 * ((freq * t) % 1.0) - 1.0')
A('        elif wave == "noise":')
A('            v = random.random() * 2.0 - 1.0')
A('        sample = int(max(-32767, min(32767, v * vol * env * 32767)))')
A('        b = struct.pack("<h", sample)')
A('        buf[i*2]   = b[0]')
A('        buf[i*2+1] = b[1]')
A('    return bytes(buf)')
A('')
A('def init_sounds():')
A('    snd = {}')
A('    snd["shoot"]      = make_sound(lambda: tone(1200,0.04,0.25,"noise")  + tone(600,0.06,0.20,"square"))')
A('    snd["hit"]        = make_sound(lambda: tone(900,0.05,0.18,"square") + tone(500,0.06,0.15,"saw"))')
A('    snd["explode"]   = make_sound(lambda: tone(300,0.08,0.30,"noise")  + tone(120,0.18,0.25,"saw"))')
A('    snd["reload_s"]   = make_sound(lambda: tone(1800,0.03,0.15,"sine")   + tone(1400,0.04,0.12,"sine"))')
A('    snd["reload_d"]   = make_sound(lambda: tone(2400,0.02,0.20,"square") + tone(1600,0.05,0.18,"sine"))')
A('    snd["player_hit"] = make_sound(lambda: tone(200,0.12,0.30,"saw")    + tone(100,0.10,0.20,"noise"))')
A('    snd["level_up"]   = make_sound(lambda: tone(523,0.10,0.25,"sine")   + tone(659,0.10,0.25,"sine") + tone(784,0.20,0.30,"sine"))')
A('    snd["game_over"]  = make_sound(lambda: tone(400,0.15,0.30,"sine")   + tone(300,0.15,0.25,"sine") + tone(180,0.40,0.30,"saw"))')
A('    snd["pickup"]    = make_sound(lambda: tone(1000,0.04,0.18,"sine")  + tone(1400,0.06,0.20,"sine"))')
A('    snd["empty"]      = make_sound(lambda: tone(200,0.06,0.20,"square"))')
A('    snd["boss_warn"]  = make_sound(lambda: tone(150,0.30,0.35,"saw")    + tone(100,0.40,0.30,"noise"))')
A('    snd["boss_fire"]  = make_sound(lambda: tone(400,0.05,0.20,"noise")  + tone(250,0.06,0.15,"square"))')
A('    snd["boss_die"]   = make_sound(lambda: tone(200,0.15,0.35,"noise")  + tone(80,0.40,0.30,"saw"))')
A('    return snd')
A('')
A('# === Cover ===')
A('class Cover:')
A('    __slots__ = ("rect",)')
A('    def __init__(s, x, y, w, h):')
A('        s.rect = pygame.Rect(x, y, w, h)')
A('    def draw(s, surf):')
A('        pygame.draw.rect(surf, (65,65,90),   s.rect, border_radius=4)')
A('        pygame.draw.rect(surf, (90,90,120),  s.rect, 2, border_radius=4)')
A('    def blocks_circle(s, x, y, r):')
A('        cx = clamp(x, s.rect.left,   s.rect.right)')
A('        cy = clamp(y, s.rect.top,    s.rect.bottom)')
A('        return (cx-x)**2 + (cy-y)**2 < r*r')
A('    def blocks_point(s, x, y, margin=0):')
A('        return s.rect.inflate(margin*2, margin*2).collidepoint(x, y)')
A('')
A('# === Particle ===')
A('class Particle:')
A('    __slots__ = ("x","y","vx","vy","life","max_life","color","r")')
A('    def __init__(s, x, y, color, spd=2.5, life=22):')
A('        a  = random.uniform(0, math.pi*2)')
A('        sp = random.uniform(spd*0.3, spd)')
A('        s.x, s.y = x, y')
A('        s.vx = math.cos(a)*sp; s.vy = math.sin(a)*sp')
A('        s.life = s.max_life = life + random.randint(-4, 4)')
A('        s.color = color; s.r = random.randint(2, 5)')
A('    def update(s):')
A('        s.x += s.vx; s.y += s.vy')
A('        s.vx *= 0.91; s.vy *= 0.91; s.life -= 1')
A('    def draw(s, surf):')
A('        if s.life <= 0: return')
A('        alpha = max(0.15, s.life / s.max_life)')
A('        r = max(1, int(s.r * alpha))')
A('        c = tuple(int(v*alpha) for v in s.color)')
A('        pygame.draw.circle(surf, c, (int(s.x), int(s.y)), r)')
A('')
A('# === Bullet ===')
A('class Bullet:')
A('    __slots__ = ("x","y","vx","vy","alive","dmg")')
A('    def __init__(s, x, y, angle, dmg=1):')
A('        s.x, s.y = float(x), float(y)')
A('        s.vx = math.cos(angle) * BULLET_SPD')
A('        s.vy = math.sin(angle) * BULLET_SPD')
A('        s.alive = True; s.dmg = dmg')
A('    def update(s, covers, g_br):')
A('        s.x += s.vx; s.y += s.vy')
A('        if not (-30 <= s.x <= W+30 and -30 <= s.y <= H+30):')
A('            s.alive = False; return')
A('        for cv in covers:')
A('            if cv.blocks_circle(s.x, s.y, g_br + 2):')
A('                s.alive = False; return')
A('    def draw(s, surf, g_br):')
A('        if not s.alive: return')
A('        br = max(1, g_br)')
A('        pygame.draw.circle(surf, C_BULLET, (int(s.x), int(s.y)), br)')
A('        tx = int(s.x - s.vx * 1.8)')
A('        ty = int(s.y - s.vy * 1.8)')
A('        pygame.draw.line(surf, (190,175,35), (tx,ty), (int(s.x),int(s.y)), 2)')
A('')
A('# === BossBullet ===')
A('class BossBullet:')
A('    __slots__ = ("x","y","vx","vy","alive","r")')
A('    def __init__(s, x, y, angle, spd=BOSS_BUL_SPD):')
A('        s.x, s.y = float(x), float(y)')
A('        s.vx = math.cos(angle) * spd')
A('        s.vy = math.sin(angle) * spd')
A('        s.alive = True; s.r = 7')
A('    def update(s, covers):')
A('        s.x += s.vx; s.y += s.vy')
A('        if not (-40 <= s.x <= W+40 and -40 <= s.y <= H+40):')
A('            s.alive = False; return')
A('        for cv in covers:')
A('            if cv.blocks_circle(s.x, s.y, s.r + 2):')
A('                s.alive = False; return')
A('    def draw(s, surf):')
A('        if not s.alive: return')
A('        pygame.draw.circle(surf, C_BOSS_BUL, (int(s.x), int(s.y)), s.r)')
A('        pygame.draw.circle(surf, C_WARN, (int(s.x), int(s.y)), s.r, 2)')
A('')
A('# === Enemy ===')
A('class Enemy:')
A('    __slots__ = ("x","y","hp","max_hp","spd","r","kind","alive","flash","color")')
A('    def __init__(s, kind, covers):')
A('        s.kind = kind; s.alive = True; s.flash = 0')
A('        for _ in range(200):')
A('            edge = random.randint(0, 3)')
A('            if   edge == 0: sx, sy = random.uniform(40,W-40), -30')
A('            elif edge == 1: sx, sy = W+30, random.uniform(40,H-40)')
A('            elif edge == 2: sx, sy = random.uniform(40,W-40), H+30')
A('            else:           sx, sy = -30, random.uniform(40,H-40)')
A('            ok = True')
A('            for cv in covers:')
A('                if cv.blocks_point(sx, sy, 20): ok = False; break')
A('            if ok:')
A('                s.x, s.y = sx, sy; break')
A('        else:')
A('            s.x, s.y = W+30, random.uniform(40,H-40)')
A('        if   kind == 0:')
A('            s.hp=s.max_hp=2; s.spd=random.uniform(1.2,1.9); s.r=12; s.color=C_E1')
A('        elif kind == 1:')
A('            s.hp=s.max_hp=1; s.spd=random.uniform(2.5,3.6); s.r=9;  s.color=C_E2')
A('        else:')
A('            s.hp=s.max_hp=5; s.spd=random.uniform(0.5,0.9); s.r=18; s.color=C_E3')
A('    def update(s, px, py, covers):')
A('        a = angle_to((s.x,s.y), (px,py))')
A('        nx = s.x + math.cos(a)*s.spd')
A('        ny = s.y + math.sin(a)*s.spd')
A('        for cv in covers:')
A('            if cv.blocks_point(nx, ny, s.r+2):')
A('                nx2 = s.x + math.cos(a)*s.spd; ny2 = s.y')
A('                if not any(cv2.blocks_point(nx2,ny2,s.r+2) for cv2 in covers):')
A('                    nx, ny = nx2, ny2')
A('                else:')
A('                    nx2b = s.x; ny2b = s.y + math.sin(a)*s.spd')
A('                    if not any(cv2.blocks_point(nx2b,ny2b,s.r+2) for cv2 in covers):')
A('                        nx, ny = nx2b, ny2b')
A('                    else:')
A('                        nx = s.x+random.uniform(-0.5,0.5)')
A('                        ny = s.y+random.uniform(-0.5,0.5)')
A('                break')
A('        s.x, s.y = nx, ny')
A('        s.x = clamp(s.x, s.r, W-s.r)')
A('        s.y = clamp(s.y, s.r, H-s.r)')
A('        if s.flash > 0: s.flash -= 1')
A('    def hit(s, dmg):')
A('        s.hp -= dmg; s.flash = 6')
A('        if s.hp <= 0: s.alive = False')
A('    def draw(s, surf):')
A('        c = C_WARN if s.flash>0 else s.color')
A('        pygame.draw.circle(surf, c, (int(s.x),int(s.y)), s.r)')
A('        if s.r == 18:')
A('            pygame.draw.circle(surf, (90,15,110), (int(s.x),int(s.y)), s.r, 2)')
A('        if s.hp < s.max_hp:')
A('            bw = s.r*2; bx = int(s.x)-s.r; by = int(s.y)-s.r-7')
A('            pygame.draw.rect(surf, C_HP_BG, (bx,by,bw,4))')
A('            pygame.draw.rect(surf, C_HP_FG, (bx,by,max(0,int(bw*s.hp/s.max_hp)),4))')
A('')
A('# === Boss ===')
A('class Boss:')
A('    def __init__(s, lv_idx, covers):')
A('        diff = 0 if lv_idx <= 4 else 1')
A('        s.hp = BOSS_HP[diff]; s.max_hp = s.hp')
A('        s.r = BOSS_R; s.spd = 1.0 + diff * 0.3')
A('        s.alive = True; s.flash = 0')
A('        s.fire_timer = 0; s.fire_cd = BOSS_FIRE_CD[diff]')
A('        s.pattern = 0; s.pattern_timer = 0')
A('        s.move_angle = random.uniform(0, math.pi*2)')
A('        s.move_t = 0; s.x, s.y = W//2, -60')
A('        s.entering = True; s.enter_y = 80')
A('    def update(s, px, py, covers, now, boss_bullets, snd):')
A('        if s.entering:')
A('            s.y += 2.5')
A('            if s.y >= s.enter_y:')
A('                s.y = s.enter_y; s.entering = False')
A('            return')
A('        s.move_t += 1')
A('        if s.move_t > 100:')
A('            s.move_angle = random.uniform(0, math.pi*2)')
A('            s.move_t = 0')
A('        mx = math.cos(s.move_angle) * s.spd * 0.5')
A('        my = math.sin(s.move_angle) * s.spd * 0.3')
A('        nx = s.x + mx; ny = s.y + my')
A('        nx = clamp(nx, s.r+20, W-s.r-20)')
A('        ny = clamp(ny, s.r+10, H*0.45)')
A('        ok = True')
A('        for cv in covers:')
A('            if cv.blocks_point(nx, ny, s.r+4):')
A('                ok = False; break')
A('        if ok: s.x, s.y = nx, ny')
A('        else: s.move_angle += math.pi')
A('        if now - s.fire_timer >= s.fire_cd:')
A('            s.fire_timer = now')
A('            s._fire(px, py, boss_bullets, snd)')
A('        if now - s.pattern_timer > 3500:')
A('            s.pattern = (s.pattern + 1) % 3')
A('            s.pattern_timer = now')
A('        if s.flash > 0: s.flash -= 1')
A('    def _fire(s, px, py, boss_bullets, snd):')
A('        if snd: snd["boss_fire"].play()')
A('        base = angle_to((s.x, s.y), (px, py))')
A('        if s.pattern == 0:')
A('            for i in range(5):')
A('                a = base + (i-2) * 0.20')
A('                boss_bullets.append(BossBullet(s.x, s.y, a))')
A('        elif s.pattern == 1:')
A('            for i in range(14):')
A('                a = i * math.pi * 2 / 14')
A('                boss_bullets.append(BossBullet(s.x, s.y, a, BOSS_BUL_SPD*0.7))')
A('        else:')
A('            base2 = base + pygame.time.get_ticks() * 0.0005')
A('            for i in range(4):')
A('                a = base2 + i * math.pi/2')
A('                boss_bullets.append(BossBullet(s.x, s.y, a, BOSS_BUL_SPD*1.1))')
A('    def hit(s, dmg):')
A('        s.hp -= dmg; s.flash = 6')
A('        if s.hp <= 0: s.alive = False')
A('    def draw(s, surf):')
A('        pulse = int(abs(math.sin(pygame.time.get_ticks() * 0.004)) * 25)')
A('        cx, cy = int(s.x), int(s.y)')
A('        pygame.draw.circle(surf, (255,50+pulse,30), (cx,cy), s.r+4, 3)')
A('        body = C_WARN if s.flash>0 else C_BOSS')
A('        pygame.draw.circle(surf, body, (cx,cy), s.r)')
A('        pygame.draw.circle(surf, C_BOSS_2, (cx,cy), s.r-10, 2)')
A('        for ex in (cx-12, cx+12):')
A('            pygame.draw.circle(surf, (255,255,0), (ex, cy-6), 5)')
A('            pygame.draw.circle(surf, (0,0,0),     (ex, cy-6), 2)')
A('        bw = W-100; bx = 50; by = 6')
A('        pygame.draw.rect(surf, C_HP_BG, (bx,by,bw,12), border_radius=3)')
A('        fw = max(0, int(bw * s.hp / s.max_hp))')
A('        if fw > 0:')
A('            pygame.draw.rect(surf, C_BOSS, (bx,by,fw,12), border_radius=3)')
A('        pygame.draw.rect(surf, C_TEXT_D, (bx,by,bw,12), 1, border_radius=3)')
A('        ft = pygame.font.SysFont("consolas", 10, bold=True)')
A('        tl = ft.render("BOSS", True, C_TEXT)')
A('        surf.blit(tl, (bx-50, by))')
A('')
A('# === Player ===')
A('class Player:')
A('    def __init__(s, mag_size, reserve):')
A('        s.x=W//2; s.y=H//2; s.hp=8; s.hp_max=8')
A('        s.angle=0; s.alive=True; s.inv_timer=0')
A('        s.shoot_timer=0; s.mag_size=mag_size; s.ammo=mag_size')
A('        s.reserve=reserve; s.reloading=False; s.reload_start=0')
A('    def set_mag(s, ms):')
A('        s.mag_size = ms')
A('    def start_reload(s, now, snd=None):')
A('        if s.reloading or s.ammo>=s.mag_size or s.reserve<=0: return')
A('        s.reloading=True; s.reload_start=now')
A('        if snd: snd["reload_s"].play()')
A('    def tick_reload(s, now, snd=None):')
A('        if s.reloading and now - s.reload_start >= g_reload_ms:')
A('            need = s.mag_size - s.ammo')
A('            take = min(need, s.reserve)')
A('            s.ammo += take; s.reserve -= take')
A('            s.reloading = False')
A('            if snd: snd["reload_d"].play()')
A('    def update(s, held, mx, my, now, covers, snd=None):')
A('        dx=dy=0')
A('        if held["up"]:    dy-=1')
A('        if held["down"]:  dy+=1')
A('        if held["left"]:  dx-=1')
A('        if held["right"]: dx+=1')
A('        if dx or dy:')
A('            l=math.sqrt(dx*dx+dy*dy)')
A('            nx=s.x+dx/l*PLAYER_SPD; ny=s.y+dy/l*PLAYER_SPD')
A('            ok=True')
A('            for cv in covers:')
A('                if cv.blocks_point(nx,ny,PLAYER_R+1): ok=False; break')
A('            if ok: s.x,s.y=nx,ny')
A('            else:')
A('                if dx and not any(cv.blocks_point(s.x+dx/l*PLAYER_SPD,s.y,PLAYER_R+1) for cv in covers):')
A('                    s.x=nx')
A('                if dy and not any(cv.blocks_point(s.x,s.y+dy/l*PLAYER_SPD,PLAYER_R+1) for cv in covers):')
A('                    s.y=ny')
A('        s.x=clamp(s.x,PLAYER_R,W-PLAYER_R)')
A('        s.y=clamp(s.y,PLAYER_R,H-PLAYER_R)')
A('        s.angle = angle_to((s.x,s.y),(mx,my))')
A('        s.tick_reload(now, snd)')
A('        if s.inv_timer>0: s.inv_timer-=1')
A('    def try_shoot(s, now, bullets, multi, snd, g_scd, g_br, g_bd):')
A('        if s.reloading: return')
A('        if s.ammo <= 0:')
A('            if snd: snd["empty"].play()')
A('            return')
A('        if now - s.shoot_timer < g_scd: return')
A('        if len(bullets) >= MAX_BULLETS: return')
A('        s.shoot_timer = now')
A('        if not getattr(s, "inf_ammo", False): s.ammo -= 1')
A('        bullets.append(Bullet(s.x, s.y, s.angle, g_bd))')
A('        if snd: snd["shoot"].play()')
A('        if multi:')
A('            bullets.append(Bullet(s.x,s.y,s.angle+0.12, g_bd))')
A('            bullets.append(Bullet(s.x,s.y,s.angle-0.12, g_bd))')
A('    def take_damage(s, snd=None):')
A('        if not s.alive: return')
A('        if getattr(s, "invincible", False): return')
A('        if s.inv_timer > 0: return')
A('        s.hp -= 1; s.inv_timer = 90')
A('        if snd: snd["player_hit"].play()')
A('        if s.hp <= 0: s.alive = False')
A('    def draw(s, surf, g_rld):')
A('        blink = s.inv_timer>0 and (s.inv_timer%8<4)')
A('        c = C_TEXT_D if blink else C_PLAYER')
A('        pygame.draw.circle(surf,c,(int(s.x),int(s.y)),PLAYER_R)')
A('        gx=int(s.x+math.cos(s.angle)*(PLAYER_R+8))')
A('        gy=int(s.y+math.sin(s.angle)*(PLAYER_R+8))')
A('        pygame.draw.line(surf,C_PLAYER_G,(int(s.x),int(s.y)),(gx,gy),4)')
A('        if s.reloading:')
A('            prog=min(1.0,(pygame.time.get_ticks()-s.reload_start)/g_rld)')
A('            bw=30; bx=int(s.x)-15; by=int(s.y)+PLAYER_R+6')
A('            pygame.draw.rect(surf,C_HP_BG,(bx,by,bw,5))')
A('            pygame.draw.rect(surf,(80,180,255),(bx,by,int(bw*prog),5))')
A('')
A('# === Level helpers ===')
A('def spawn_covers(n):')
A('    covers=[]')
A('    safe = pygame.Rect(W//2-120, H//2-120, 240, 240)')
A('    for _ in range(n):')
A('        for attempt in range(80):')
A('            w=random.randint(40,100); h=random.randint(40,100)')
A('            x=random.randint(90,W-90-w); y=random.randint(90,H-90-h)')
A('            rect=pygame.Rect(x,y,w,h)')
A('            if rect.colliderect(safe): continue')
A('            if any(rect.colliderect(c.rect.inflate(24,24)) for c in covers): continue')
A('            covers.append(Cover(x,y,w,h)); break')
A('    return covers')
A('')
A('def make_level(lv_idx):')
A('    idx = min(lv_idx, len(LEVELS)-1)')
A('    t,sp,_,mg,rs = LEVELS[idx]')
A('    covs = spawn_covers(LEVELS[idx][2])')
A('    return idx,0,mg,rs,covs,sp,t')
A('')
A('# === Drawing ===')
A('def draw_hud(surf, font, sfont, player, lv_num, kills, kt, fps, boss):')
A('    if fps > 0:')
A('        fc = (80,220,80) if fps>=55 else ((255,215,50) if fps>=30 else (255,90,90))')
A('        ft = sfont.render("FPS "+str(int(fps)), True, fc)')
A('        surf.blit(ft, (W-ft.get_width()-8, 36))')
A('    for i in range(player.hp_max):')
A('        c = C_HP_FG if i<player.hp else C_HP_BG')
A('        pygame.draw.circle(surf,c,(24+i*26,20),8)')
A('    t = font.render("LV."+str(lv_num),True,C_ACCENT)')
A('    surf.blit(t,(W-20-t.get_width(),14))')
A('    kt2 = sfont.render(str(kills)+"/"+str(kt),True,C_TEXT)')
A('    surf.blit(kt2,(W//2-kt2.get_width()//2,12))')
A('    ac = C_WARN if player.ammo==0 else (C_ACCENT if player.ammo<=4 else C_TEXT)')
A('    a = sfont.render(str(player.ammo)+"/"+str(player.mag_size),True,ac)')
A('    surf.blit(a,(14,38))')
A('    r = sfont.render("RES "+str(player.reserve),True,C_TEXT_D)')
A('    surf.blit(r,(14,56))')
A('    if player.ammo==0 and player.reserve>0 and not player.reloading:')
A('        h=sfont.render("[M] RELOAD",True,C_WARN)')
A('        surf.blit(h,(W//2-h.get_width()//2,36))')
A('    if player.reloading:')
A('        rl=sfont.render("RELOADING...",True,(80,180,255))')
A('        surf.blit(rl,(W//2-rl.get_width()//2,36))')
A('    if boss and boss.alive:')
A('        wt = font.render("!! BOSS !!", True, C_WARN)')
A('        surf.blit(wt, (W//2-wt.get_width()//2, 22))')
A('    fl=[]')
A('    if getattr(player,"invincible",False): fl.append("INV")')
A('    if getattr(player,"inf_ammo",False):   fl.append("INF")')
A('    if g_shoot_cd != 160:               fl.append("CD:"+str(g_shoot_cd))')
A('    if g_bullet_r != 4:               fl.append("BR:"+str(g_bullet_r))')
A('    if g_bullet_dmg != 1:              fl.append("DMG:"+str(g_bullet_dmg))')
A('    if g_reload_ms != 1400:            fl.append("RL:"+str(g_reload_ms))')
A('    if fl:')
A('        ct = sfont.render("  ".join(fl), True, (255,210,50))')
A('        surf.blit(ct, (W-ct.get_width()-8, H-22))')
A('')
A('def draw_grid(surf):')
A('    for x in range(0,W,40): pygame.draw.line(surf,C_GRID,(x,0),(x,H))')
A('    for y in range(0,H,40): pygame.draw.line(surf,C_GRID,(0,y),(W,y))')
A('')
A('def draw_boss_warn(surf, bigfont, font, timer):')
A('    alpha = int(abs(math.sin(timer*0.008)) * 180) + 40')
A('    ov = pygame.Surface((W,H), pygame.SRCALPHA)')
A('    ov.fill((60,0,0,min(140,alpha)))')
A('    surf.blit(ov,(0,0))')
A('    t1 = bigfont.render("WARNING", True, C_WARN)')
A('    t2 = font.render("BOSS INCOMING!", True, C_BOSS_2)')
A('    surf.blit(t1, (W//2-t1.get_width()//2, H//2-60))')
A('    surf.blit(t2, (W//2-t2.get_width()//2, H//2+10))')
A('')
A('def draw_boss_kill(surf, bigfont, font, timer):')
A('    alpha = min(200, max(0, int(timer*2.5)))')
A('    ov = pygame.Surface((W,H), pygame.SRCALPHA)')
A('    ov.fill((0,60,0,alpha))')
A('    surf.blit(ov,(0,0))')
A('    t1 = bigfont.render("BOSS DEFEATED!", True, C_ACCENT)')
A('    t2 = font.render("REWARD: +50 AMMO  +2 HP", True, (80,220,80))')
A('    surf.blit(t1, (W//2-t1.get_width()//2, H//2-50))')
A('    surf.blit(t2, (W//2-t2.get_width()//2, H//2+20))')
A('')
A('def draw_pause(surf,font,sfont,sel):')
A('    ov=pygame.Surface((W,H),pygame.SRCALPHA); ov.fill(C_POVER_BG); surf.blit(ov,(0,0))')
A('    t=font.render("PAUSED",True,C_TEXT)')
A('    surf.blit(t,(W//2-t.get_width()//2,H//2-110))')
A('    for i,(cn,_) in enumerate([("CONTINUE","CONTINUE"),("RESTART","RESTART"),("QUIT","QUIT")]):')
A('        y=H//2-18+i*52; col=C_ACCENT if i==sel else C_TEXT')
A('        if i==sel:')
A('            r=pygame.Rect(W//2-100,y-17,200,38)')
A('            pygame.draw.rect(surf,(40,40,60),r,border_radius=8)')
A('        ti=font.render(cn,True,col)')
A('        surf.blit(ti,(W//2-ti.get_width()//2,y-ti.get_height()//2))')
A('    h=sfont.render("W/S:Select  ENTER:Confirm  ESC:Resume",True,C_TEXT_D)')
A('    surf.blit(h,(W//2-h.get_width()//2,H//2+130))')
A('')
A('def draw_transition(surf,bigfont,font,lv_num,mag_up):')
A('    ov=pygame.Surface((W,H),pygame.SRCALPHA); ov.fill((0,0,0,140)); surf.blit(ov,(0,0))')
A('    t1=bigfont.render("LEVEL  "+str(lv_num),True,C_ACCENT)')
A('    surf.blit(t1,(W//2-t1.get_width()//2,H//2-50))')
A('    if mag_up:')
A('        t2=font.render("MAGAZINE UPGRADED",True,(80,200,120))')
A('        surf.blit(t2,(W//2-t2.get_width()//2,H//2+10))')
A('')
A('def draw_gameover(surf,bigfont,font,sfont,score,lv_num):')
A('    ov=pygame.Surface((W,H),pygame.SRCALPHA); ov.fill((0,0,0,180)); surf.blit(ov,(0,0))')
A('    t1=bigfont.render("GAME OVER",True,C_WARN)')
A('    t2=font.render("SCORE "+str(score).zfill(6),True,C_TEXT)')
A('    t3=font.render("LEVEL "+str(lv_num),True,C_TEXT_D)')
A('    t4=sfont.render("R:RESTART  Q:QUIT",True,C_TEXT_D)')
A('    surf.blit(t1,(W//2-t1.get_width()//2,H//2-110))')
A('    surf.blit(t2,(W//2-t2.get_width()//2,H//2-30))')
A('    surf.blit(t3,(W//2-t3.get_width()//2,H//2+10))')
A('    surf.blit(t4,(W//2-t4.get_width()//2,H//2+70))')
A('')
A('# === Cheat config ===')
A('CHEAT_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "cheat_cfg.json")')
A('cheat_last_v = -1')
A('def read_cheat():')
A('    try:')
A('        if os.path.exists(CHEAT_FILE):')
A('            with open(CHEAT_FILE, "r", encoding="utf-8") as f: return json.load(f)')
A('    except Exception: pass')
A('    return None')
A('def write_cheat(cfg):')
A('    try:')
A('        cfg["apply"] = False')
A('        with open(CHEAT_FILE, "w", encoding="utf-8") as f: json.dump(cfg, f, indent=2)')
A('    except Exception: pass')
A('')
A('# === Main ===')
A('def game():')
A('    global g_bullet_r, g_shoot_cd, g_bullet_dmg, g_reload_ms')
A('    pygame.init()')
A('    pygame.mixer.init(frequency=SR, size=-16, channels=1, buffer=512)')
A('    pygame.mixer.set_num_channels(8)')
A('    snd = init_sounds()')
A('    surf = pygame.display.set_mode((W,H))')
A('    pygame.display.set_caption("TopDown Shooter v4")')
A('    clock = pygame.time.Clock()')
A('    def mkf(size, bold=False):')
A('        try: return pygame.font.SysFont("consolas", size, bold=bold)')
A('        except: return pygame.font.Font(None, size+(4 if bold else 0))')
A('    font=mkf(22,True); sfont=mkf(15); bigfont=mkf(48,True)')
A('    global cheat_last_v')
A('    fc=[0]')
A('    def apply_cheat(p):')
A('        nonlocal fc')
A('        fc[0]+=1')
A('        if fc[0]%6!=0: return')
A('        global g_bullet_r,g_shoot_cd,g_bullet_dmg,g_reload_ms,cheat_last_v')
A('        cfg=read_cheat()')
A('        if not cfg: return')
A('        v=cfg.get("_version",0)')
A('        if v==cheat_last_v: return')
A('        cheat_last_v=v')
A('        p.invincible=bool(cfg.get("invincible",False))')
A('        p.inf_ammo=bool(cfg.get("inf_ammo",False))')
A('        global g_shoot_cd; g_shoot_cd=max(0,int(cfg.get("shoot_cd",160)))')
A('        global g_bullet_r; g_bullet_r=max(1,int(cfg.get("bullet_r",4)))')
A('        global g_bullet_dmg; g_bullet_dmg=max(1,int(cfg.get("bullet_dmg",1)))')
A('        global g_reload_ms; g_reload_ms=max(50,int(cfg.get("reload_ms",1400)))')
A('        if cfg.get("apply",False):')
A('            nh=max(1,int(cfg.get("hp",p.hp))); nhm=max(1,int(cfg.get("hp_max",p.hp_max)))')
A('            nm=max(1,int(cfg.get("mag_size",p.mag_size)))')
A('            p.hp=min(nh,nhm); p.hp_max=nhm')
A('            if nm!=p.mag_size: p.set_mag(nm); p.ammo=min(p.ammo,nm)')
A('            if p.inf_ammo: p.ammo=p.mag_size')
A('            write_cheat(cfg)')
A('    def reset_all():')
A('        idx,_,mg,rs,cv,sp,kt=make_level(0)')
A('        p=Player(mg,rs)')
A('        return p,[],[],[],0,idx,0,kt,sp,cv,pygame.time.get_ticks(),None,[]')
A('    (player,bullets,enemies,particles,score,lv_idx,kills,kt,spd,covers,last_spawn,boss,boss_bullets)=reset_all()')
A('    game_over=False; paused=False; pause_sel=0; shooting=False')
A('    trans_t=0; trans_up=False; boss_warn_t=0; boss_kill_t=0')
A('    held={"up":False,"down":False,"left":False,"right":False}')
A('    MOVE_KEYS={pygame.K_w:"up",pygame.K_UP:"up",pygame.K_s:"down",pygame.K_DOWN:"down",pygame.K_a:"left",pygame.K_LEFT:"left",pygame.K_d:"right",pygame.K_RIGHT:"right"}')
A('    def try_spawn():')
A('        nonlocal last_spawn,spd')
A('        now=pygame.time.get_ticks()')
A('        if now-last_spawn<spd: return')
A('        if boss and boss.alive: return')
A('        last_spawn=now')
A('        w=[6,2,0] if lv_idx<=1 else ([4,4,2] if lv_idx<=4 else [3,4,3])')
A('        enemies.append(Enemy(random.choices([0,1,2],weights=w)[0], covers))')
A('        if lv_idx>=3 and random.random()<0.25: enemies.append(Enemy(0,covers))')
A('    cur_fps=0.0')
A('    while True:')
A('        now=pygame.time.get_ticks()')
A('        mx,my=pygame.mouse.get_pos()')
A('        cur_fps=clock.get_fps()')
A('        for ev in pygame.event.get():')
A('            if ev.type==pygame.QUIT: pygame.quit(); sys.exit()')
A('            elif ev.type==pygame.KEYDOWN:')
A('                if game_over:')
A('                    if ev.key==pygame.K_r: (player,bullets,enemies,particles,score,lv_idx,kills,kt,spd,covers,last_spawn,boss,boss_bullets)=reset_all(); game_over=False; paused=False; trans_t=0; trans_up=False; boss_warn_t=0; boss_kill_t=0')
A('                    elif ev.key==pygame.K_q: pygame.quit(); sys.exit()')
A('                    continue')
A('                if ev.key==pygame.K_ESCAPE: paused=not paused; pause_sel=0; continue')
A('                if paused:')
A('                    if ev.key in (pygame.K_w,pygame.K_UP):   pause_sel=(pause_sel-1)%3')
A('                    elif ev.key in (pygame.K_s,pygame.K_DOWN): pause_sel=(pause_sel+1)%3')
A('                    elif ev.key in (pygame.K_RETURN,pygame.K_SPACE,pygame.K_KP_ENTER):')
A('                        if pause_sel==0: paused=False')
A('                        elif pause_sel==1: (player,bullets,enemies,particles,score,lv_idx,kills,kt,spd,covers,last_spawn,boss,boss_bullets)=reset_all(); paused=False; game_over=False; trans_t=0; trans_up=False; boss_warn_t=0; boss_kill_t=0')
A('                        elif pause_sel==2: pygame.quit(); sys.exit()')
A('                    continue')
A('                if ev.key in MOVE_KEYS: held[MOVE_KEYS[ev.key]]=True')
A('                elif ev.key==pygame.K_m: player.start_reload(now,snd)')
A('                elif ev.key==pygame.K_r: (player,bullets,enemies,particles,score,lv_idx,kills,kt,spd,covers,last_spawn,boss,boss_bullets)=reset_all(); game_over=False; trans_t=0; trans_up=False; boss_warn_t=0; boss_kill_t=0')
A('            elif ev.type==pygame.KEYUP:')
A('                if ev.key in MOVE_KEYS: held[MOVE_KEYS[ev.key]]=False')
A('            elif ev.type==pygame.MOUSEBUTTONDOWN and ev.button==1:')
A('                if not paused and not game_over: shooting=True')
A('            elif ev.type==pygame.MOUSEBUTTONUP and ev.button==1: shooting=False')
A('        if paused and not game_over:')
A('            surf.fill(C_BG); draw_grid(surf)')
A('            for cv in covers: cv.draw(surf)')
A('            for p in particles: p.draw(surf)')
A('            for e in enemies: e.draw(surf)')
A('            for bb in boss_bullets: bb.draw(surf)')
A('            if boss and boss.alive: boss.draw(surf)')
A('            for b in bullets: b.draw(surf,g_bullet_r)')
A('            player.draw(surf,g_reload_ms)')
A('            draw_hud(surf,font,sfont,player,lv_idx+1,kills,kt,cur_fps,boss)')
A('            draw_pause(surf,font,sfont,pause_sel)')
A('            pygame.display.flip(); clock.tick(FPS); continue')
A('        if game_over:')
A('            surf.fill(C_BG); draw_grid(surf)')
A('            for cv in covers: cv.draw(surf)')
A('            for p in particles: p.draw(surf)')
A('            for e in enemies: e.draw(surf)')
A('            if boss and boss.alive: boss.draw(surf)')
A('            player.draw(surf,g_reload_ms)')
A('            draw_hud(surf,font,sfont,player,lv_idx+1,kills,kt,cur_fps,boss)')
A('            draw_gameover(surf,bigfont,font,sfont,score,lv_idx+1)')
A('            pygame.display.flip(); clock.tick(FPS); continue')
A('        if boss_warn_t>0:')
A('            boss_warn_t-=1')
A('            surf.fill(C_BG); draw_grid(surf)')
A('            player.draw(surf,g_reload_ms)')
A('            draw_hud(surf,font,sfont,player,lv_idx+1,kills,kt,cur_fps,boss)')
A('            draw_boss_warn(surf,bigfont,font,boss_warn_t)')
A('            pygame.display.flip(); clock.tick(FPS); continue')
A('        if boss_kill_t>0:')
A('            boss_kill_t-=1')
A('            surf.fill(C_BG); draw_grid(surf)')
A('            for cv in covers: cv.draw(surf)')
A('            for p in particles: p.draw(surf)')
A('            player.draw(surf,g_reload_ms)')
A('            draw_hud(surf,font,sfont,player,lv_idx+1,kills,kt,cur_fps,boss)')
A('            draw_boss_kill(surf,bigfont,font,boss_kill_t)')
A('            if boss_kill_t==0: boss=None')
A('            pygame.display.flip(); clock.tick(FPS); continue')
A('        apply_cheat(player)')
A('        player.update(held,mx,my,now,covers,snd)')
A('        multi=lv_idx>=1')
A('        if shooting: player.try_shoot(now,bullets,multi,snd,g_shoot_cd,g_bullet_r,g_bullet_dmg)')
A('        if held.get("space"): player.try_shoot(now,bullets,multi,snd,g_shoot_cd,g_bullet_r,g_bullet_dmg)')
A('        for b in bullets: b.update(covers,g_bullet_r)')
A('        bullets=[b for b in bullets if b.alive]')
A('        for bb in boss_bullets: bb.update(covers)')
A('        boss_bullets=[bb for bb in boss_bullets if bb.alive]')
A('        if not (boss and boss.alive): try_spawn()')
A('        for e in enemies: e.update(player.x,player.y,covers)')
A('        if boss and boss.alive: boss.update(player.x,player.y,covers,now,boss_bullets,snd)')
A('        for b in bullets:')
A('            if not b.alive: continue')
A('            for e in enemies:')
A('                if not e.alive: continue')
A('                if dist((b.x,b.y),(e.x,e.y)) < e.r+g_bullet_r:')
A('                    e.hit(b.dmg); b.alive=False')
A('                    if snd: snd["hit"].play()')
A('                    for _ in range(5): particles.append(Particle(e.x,e.y,e.color))')
A('                    if not e.alive:')
A('                        if snd: snd["explode"].play()')
A('                        score+=(10 if e.r==12 else 15 if e.r==9 else 30); kills+=1')
A('                        for _ in range(10): particles.append(Particle(e.x,e.y,e.color,spd=3))')
A('                        if random.random()<0.35: player.reserve+=random.randint(3,8); snd["pickup"].play()')
A('                    break')
A('        for b in bullets:')
A('            if not b.alive: continue')
A('            if boss and boss.alive and not boss.entering:')
A('                if dist((b.x,b.y),(boss.x,boss.y)) < boss.r+g_bullet_r:')
A('                    boss.hit(b.dmg); b.alive=False')
A('                    if snd: snd["hit"].play()')
A('                    for _ in range(8): particles.append(Particle(b.x,b.y,C_BOSS_2))')
A('                    if not boss.alive:')
A('                        if snd: snd["boss_die"].play()')
A('                        score+=200; kills+=5')
A('                        for _ in range(30):')
A('                            particles.append(Particle(boss.x,boss.y,C_BOSS,spd=4,life=30))')
A('                            particles.append(Particle(boss.x,boss.y,C_BOSS_2,spd=3,life=25))')
A('                        player.reserve+=50; player.hp=min(player.hp+2,player.hp_max); boss_kill_t=150')
A('                    break')
A('        bullets=[b for b in bullets if b.alive]')
A('        enemies=[e for e in enemies if e.alive]')
A('        for bb in boss_bullets:')
A('            if not bb.alive: continue')
A('            if dist((bb.x,bb.y),(player.x,player.y)) < bb.r+PLAYER_R:')
A('                player.take_damage(snd); bb.alive=False')
A('                if not player.alive and not game_over: game_over=True; snd["game_over"].play()')
A('        for e in enemies:')
A('            if dist((e.x,e.y),(player.x,player.y)) < e.r+PLAYER_R:')
A('                player.take_damage(snd)')
A('                if not player.alive and not game_over: game_over=True; snd["game_over"].play()')
A('        for p in particles: p.update()')
A('        particles=[p for p in particles if p.life>0]')
A('        if kills>=kt and trans_t==0 and boss_kill_t==0:')
A('            nxt=lv_idx+1')
A('            if nxt in BOSS_LEVELS and boss is None:')
A('                trans_t=now; trans_up=False')
A('                if nxt<len(LEVELS):')
A('                    nm=LEVELS[nxt][3]')
A('                    if nm>player.mag_size: player.set_mag(nm); player.ammo=min(player.ammo,nm); trans_up=True; snd["level_up"].play()')
A('            else:')
A('                trans_t=now; trans_up=False')
A('                if nxt<len(LEVELS):')
A('                    nm=LEVELS[nxt][3]')
A('                    if nm>player.mag_size: player.set_mag(nm); player.ammo=min(player.ammo,nm); trans_up=True; snd["level_up"].play()')
A('        if trans_t and now-trans_t>1800:')
A('            lv_idx+=1')
A('            _,_,ms,rs,ncv,nspd,nkt=make_level(lv_idx)')
A('            player.set_mag(ms); player.reserve=rs')
A('            if player.ammo>ms: player.ammo=ms')
A('            covers=ncv; spd=nspd; kt=nkt; kills=0')
A('            enemies.clear(); bullets.clear(); boss_bullets.clear(); trans_t=0; trans_up=False')
A('            if lv_idx in BOSS_LEVELS:')
A('                boss=Boss(lv_idx,covers); boss_warn_t=120; snd["boss_warn"].play()')
A('            else: boss=None')
A('        surf.fill(C_BG); draw_grid(surf)')
A('        for cv in covers: cv.draw(surf)')
A('        for p in particles: p.draw(surf)')
A('        for e in enemies: e.draw(surf)')
A('        for bb in boss_bullets: bb.draw(surf)')
A('        if boss and boss.alive: boss.draw(surf)')
A('        for b in bullets: b.draw(surf,g_bullet_r)')
A('        player.draw(surf,g_reload_ms)')
A('        draw_hud(surf,font,sfont,player,lv_idx+1,kills,kt,cur_fps,boss)')
A('        if trans_t: draw_transition(surf,bigfont,font,lv_idx+2,trans_up)')
A('        pygame.display.flip()')
A('        clock.tick(FPS)')
A('')
A('if __name__=="__main__":')
A('    game()')
A('')

with open("G:/python/游戏/shooter.py", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("shooter.py written!")
print("Lines:", len(lines))
