@echo off
echo 正在检查 pygame...
C:\Python311\python.exe -c "import pygame" 2>nul || (
    echo 首次运行，安装 pygame...
    C:\Python311\python.exe -m pip install pygame
)
echo 启动游戏...
start "" "C:\Python311\pythonw.exe" "%~dp0shooter.py"
